export const START_APP = 'START_APP';
export const FETCH_UNREAD_MAILS = 'FETCH_UNREAD_MAILS';
export const FETCH_UNREAD_MAILS_BY_TYPE = 'FETCH_UNREAD_MAILS_BY_TYPE';
export const FETCH_ALL_MAILS_BY_TEXT_ENTRY = 'FETCH_ALL_MAILS_BY_TEXT_ENTRY';